site_name: Meduza Documentation

nav:
    - Home: index.md
    - Getting Started:
        - Installation: installation.md
        - Configuration: configuration.md
        - Usage: usage.md
    - Architecture: architecture.md
    - API:
        - Listener API: listener-api.md
        - Agent API: agent-api.md
        - Client API: client-api.md
    - Development:
        - Listener Development: listener-development.md
        - Agent Development: agent-development.md
theme:
    favicon: 'img/favicon.ico'
    logo: 'img/logo.png'
    name: material
    palette:
        - media: "(prefers-color-scheme: light)"
          primary: 'black'
          accent: 'white'
          toggle:
            icon: material/brightness-3
            name: Switch to dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: 'black'
          accent: 'white'
          toggle:
            icon: material/brightness-7
            name: Switch to light mode

extra:
    favicon: 'img/favicon.ico'