site_name: Meduza Documentation

nav:
    - Home: index.md
    - Getting Started:
        - Installation and Configuration: installation-and-config.md
        - Environment: environment.md
        - Usage: usage.md
    - Architecture: architecture.md
    - API:
        - Listener API: listener-api.md
        - Agent API: agent-api.md
        - Client API: client-api.md
    - Development:
        - Listener Development: listener-development.md
        - Agent Development: agent-development.md
    - Change Log: change-log.md
    
theme:
    favicon: 'img/favicon.ico'
    logo: 'img/logo.png'
    name: material
    features:
        - content.code.annotate
        - content.code.copy
    icon:
        copy: fontawesome/regular/copy
        check: fontawesome/regular/check
    palette:
        - media: "(prefers-color-scheme: light)"
          primary: 'black'
          accent: 'white'
          toggle:
            icon: material/brightness-3
            name: Switch to dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: 'black'
          accent: 'white'
          toggle:
            icon: material/brightness-7
            name: Switch to light mode

markdown_extensions:
  - codehilite
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.tilde
  - pymdownx.highlight
